### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by Rap30God** [liguoqing250/playball#2]
项目很赞，前后端分离后前端登陆页面出了点问题

**Comment by liguoqing250** [comment]
这项目有一段时间没维护了，你这边是要自己研究么？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liguoqing250/playball"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月24日(星期六) 晚上10:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [liguoqing250/playball] 项目运行不起来 (#2)





 
Closed #2.

**Comment by Rap30God** [comment]
是的，因为我本人很喜欢篮球，想为做个人学习。大佬能不能给个数据库，麻烦了。
